### ISSUE TITLE
Error failed to find TextTransform.exe

### ISSUE THREAD

**Issue by dsopko** [clariuslabs/TransformOnBuild#66]
Using Visual Studio Community 2019
Install-Package Clarius.TransformOnBuild
Run my solution with tt file I get the following error

System.Exception: Failed to find TextTransform.exe
   at Clarius.TransformOnBuild.MSBuild.Task.TransformOnBuildTask.GetTextTransformExePath()
   at Clarius.TransformOnBuild.MSBuild.Task.TransformOnBuildTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by jsiegmund** [comment]
Same here

**Comment by jimmyheaddon** [comment]
There's a [PR open](https://github.com/clariuslabs/TransformOnBuild/pull/62) that appears to address this

**Comment by johnverbiest** [comment]
Hi,

In case you are still waiting for this (or arriving here by accident). I created a fork of this project and have build and deployed the correct nuget package that includes the change above. You can find the nuget package on [https://www.nuget.org/packages/JohnVerbiest.TransformOnBuild/](https://www.nuget.org/packages/JohnVerbiest.TransformOnBuild/).

I will be accepting pull requests in hope to put some new life into this.
